version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    networks:
        - shared_network
  mariadb:
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      -  /home/lazmoud/data/db:/var/lib/mysql
    networks:
        - shared_network
  wordpress:
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      -  /home/lazmoud/data/html:/var/www/html
    networks:
      - shared_network
networks:
  shared_network:
    driver: bridge
