version: '3.8'

services:
  mariadb:
    secrets:
      - db_root_password
      - db_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      -  /home/lazmoud/data/db:/var/lib/mysql
    networks:
        - shared_network
  wordpress:
    secrets:
      - wp_admin_password
      - db_password
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      SITE_TITLE: ${SITE_TITLE}
      URL: ${URL}
      EMAIL: ${EMAIL}
      WP_USER: ${WP_USER}
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      -  /home/lazmoud/data/html:/var/www/html
    networks:
      - shared_network
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      -  /home/lazmoud/data/html:/var/www/html
    ports:
      - "443:443"
    networks:
        - shared_network
secrets:
  db_root_password:
    file: ../../secrets/db_root_password.txt
  db_password:
    file: ../../secrets/db_password.txt
  wp_admin_password:
    file: ../../secrets/wp_admin_password.txt
networks:
  shared_network:
    driver: bridge
