services:
  mariadb:
    secrets:
      - db_root_password
      - db_password
    environment:
      MARIA_DATABASE_NAME: ${MARIA_DATABASE_NAME}
      MARIA_DB_USER: ${MARIA_DB_USER}
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shared_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "health.sh"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s
  wordpress:
    secrets:
      - wp_admin_password
      - db_password
    environment:
      MARIA_DB_HOST: ${MARIA_DB_HOST}
      MARIA_DB_USER: ${MARIA_DB_USER}
      MARIA_DATABASE_NAME: ${MARIA_DATABASE_NAME}
      SITE_TITLE: ${SITE_TITLE}
      URL: ${URL}
      EMAIL: ${EMAIL}
      WP_USER: ${WP_USER}
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      -  html_data:/var/www/html
    networks:
      - shared_network
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      -  html_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - shared_network
    restart: always
    depends_on:
      - wordpress
secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

networks:
  shared_network:
    driver: bridge

volumes:
  html_data:
    driver: local
    driver_opts:
      type: none
      device: /home/lazmoud/data/html
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/lazmoud/data/db
      o: bind
